name: Release

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Release binaries
        shell: bash
        run: |
          cd target/release
          tar czvf ../../binaries-amd64.tar.gz tpe_hyperparameter_optm serving
          cd -

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: 'binaries-amd64.tar.gz'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-mac:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    
    steps:    
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          default: true
          override: true

      - name: Build
        run: cargo build --all --release

      - name: Release binaries
        shell: bash
        run: |
          cd target/release
          tar czvf ../../binaries-darwin.tar.gz tpe_hyperparameter_optm serving
          cd -

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: 'binaries-darwin.tar.gz'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
